import Head from "next/head";
import Counter from "../components/counter/Counter";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pomodoro.png" />
      </Head>

      <div
        className="h-full border-2 border-dashed border-gray-200"
        aria-hidden="true"
      />
      <main>
        <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
          <Counter />
        </div>
      </main>
    </div>
  );
}
